# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.BooleanField(),
        ),
    ]
